import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/Navbar/Navbar";

const inter = Inter({
	subsets: ["latin"],
	weight: ["400", "500", "600", "700"],
	variable: "--font-inter",
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" data-theme="light">
			<body className={`${inter.variable} antialiased`}>
				<Navbar />
				{children}
			</body>
		</html>
	);
}
